//
//  HomePresenter.swift
//  iOS-intern-assignment
//
//  Created by Pasika Pongsawaluk on 2/2/2568 BE.
//  Copyright (c) 2568 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic
{
    func presentSomething(response: Home.Something.Response)
    func presentHome(response: PhotoResponse)
}

class HomePresenter: HomePresentationLogic
{
    weak var viewController: HomeDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Home.Something.Response)
    {
        let viewModel = Home.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentHome(response: PhotoResponse){
        let photos = response.photos
        
        var viewModels: [PhotoTableViewCellViewModel] = []
        photos.forEach { photo in
            let formattedCount = photo.positiveVotesCount.formatted(.number)
            
            viewModels.append(PhotoTableViewCellViewModel(
                imageUrl: photo.imageUrl[0],
                name: photo.name,
                description: photo.description,
                positiveVotesCount: formattedCount
            ))
        }
        viewController?.displayHome(photos: viewModels)
    }
}
